module.exports = {
    justification: { parent: 'about', title: 'Justification'},
    vision: { parent: 'about', title: 'vision'},
    mission: { parent: 'about', title: 'mission'},
    objectives: { parent: 'about', title: 'objectives'},
    contact_us: { parent: 'about', title: 'contact us'},
    education: {parent: 'education', title: 'education'},
    teaching: {parent: 'education', title: 'teaching'},
    learning_activities: {parent: 'education', title: 'learning activities'},
    skills_gap: { parent: 'education', title: 'skill gap to be bridged'},
    innovations_in_pedagogy:  { parent: 'education', title: 'innovations in pedagogy'},
    degree_programmes:  { parent: 'education', title: 'degree programmes'},
    online_courses: {parent: 'education', title: 'online courses'},
    research_plan: {parent: 'research', title: 'research plan'},
    industrial_partnerships: {parent: 'research', title: 'industrial partnerships'},
    academic_partnerships: {parent: 'research', title: 'academic partnerships'},
    retention_support: {parent: 'recruit', title: 'retention and support'},
    student_recruitment: {parent: 'recruit', title: 'student recruitment'},
    staff: {parent: 'management', title: 'staff'},
    centre_operations: {parent: 'management', title: 'centre operations'},
    implementation_timeline: {parent: 'management', title: 'implementation timeline'},
    settings: {parent: 'settings', title: 'settings'}
}