module.exports = {
    'justification-for-establishing-the-centre': { data: 'justification', nav: 'about' },
    'vision': { data: 'vision', nav: 'about' },
    'mission': { data: 'mission', nav: 'about' },
    'objectives': { data: 'objectives', nav: 'about' },
    'education': { data: 'education', nav: 'education' },
    'teaching': { data: 'teaching', nav: 'education' },
    'learning-activities': { data: 'learning-activities', nav: 'education' },
    'skills-gap': { data: 'skills-gap', nav: 'education' },
    'innovations-in-pedagogy': { data: 'innovations-in-pedagogy', nav: 'education' },
    'innovations-in-assessment': { data: 'innovations-in-assessment', nav: 'education' },
    'online-courses': { data: 'online-courses', nav: 'education' },
    'research-plan': { data: 'research-plan', nav: 'research' },
    'industrial-partnerships': { data: 'industrial-partnerships', nav: 'research' },
    'academic-partnerships': { data: 'academic-partnerships', nav: 'research' },
    'retention-and-support': { data: 'retention-support', nav: 'recruit' },
    'student-recruitment': { data: 'student-recruitment', nav: 'recruit' },
    'staff-development': { data: 'staff', nav: 'management' },
    'centre-operations': { data: 'centre-operations', nav: 'management' },
    'implementation-timeline': { data: 'implementation-timeline', nav: 'management' },
}